export default {
  headerTitle: '시술노트',
  hairStyleTitle: '모발 타입',
  hairStyle3: '생머리',
  hairStyle2: '반곱슬',
  hairStyle1: '곱슬',
  hairThickTitle: '모발 두께',
  hairThick3: '얇음',
  hairThick2: '보통',
  hairThick1: '굵음',
  scalpStateTitle: '두피 상태',
  scalpStateGuide: ' ※중복선택 가능',
  scalpStates: [
    '중성',
    '건성',
    '지성',
    '민감성',
    '비듬',
  ],
  beforeDamageTitle: '시술 전 손상도',
  beforeDamages: [
    '건강',
    '보통',
    '손상',
    '극손상',
  ],
  beforeDamagesQuestion: '모발 상태의 기준이 무엇인가요?',
  nextVisitTitle: '다음 방문일',
  unitMonth: '개월',
  unitWeek: '주 뒤',
  afterNoteTitle: '시술정보',
  afterNoteHint: `어떤 시술이 진행되었는지 고객님께 알려주세요. 고객 맞춤형 메시지를 작성할수록 재방문률이 올라갑니다!\nex)\n탈색모인 고객님을 위해 복구펌 진행하였습니다. 손상도가 적은 약품이라 만족하실거예요^^ 3개월 뒤, 머리가 건조한 느낌이 들 때 다시 방문해주세요!`,
  private: ' [비공개]',
  beforeImage: '시술 전(선택)',
  afterImage: '시술 후(선택)',
  productNoteTitle: '사용제품(제품명/번호/그램수)',
  productNoteHint: `시술 시 사용한 제품의 정보를 기록하세요. 이 정보는 다른 디자이너나 고객에게 공개되지 않습니다.\nex)\n로레알 마지렐/ 6.07/ 150g`,
  customerNoteTitle: (name) => `${name}고객님의 맞춤 스타일링 & 케어`,
  customerNoteHint: '고객님만을 위한 시술 후 손질법을 알려주세요.',
  privateNoteTitle: '개인메모',
  privateNoteHint: `고객에 관한 정보를 자유롭게 기입해주세요. 해당 정보는 고객에게 공개되지 않습니다.\nex)\n- 옆머리 뜨는 것이 콤플렉스\n- 민감성 두피라 주의 필요`,
  save: '저장',
  takePhoto: '사진 촬영',
  choosePhoto: '앨범에서 사진 선택',
  guide: `안심하세요!\n아래 내용은 다른 디자이너에게 공개되지 않습니다.`,
  dateUnits: ['년', '월', '일']
}
